# Generated by Django 4.2.6 on 2023-11-17 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0015_city_isfeatured_alter_country_isfeatured'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trendingPlaces', to='cities_light.city')),
            ],
        ),
        migrations.CreateModel(
            name='MultiImagesTrendingPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='trending_places/photos/')),
                ('trendingPlace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.trendingplace')),
            ],
        ),
        migrations.CreateModel(
            name='MultiImagesCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='countries/photos/')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='cities_light.country')),
            ],
        ),
        migrations.CreateModel(
            name='MultiImagesCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='cities/photos/')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.city')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameEvent', models.CharField(help_text='Put Name Of Events', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('sale_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('isFeatured', models.BooleanField(default=False)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='cities_light.country')),
            ],
        ),
        migrations.CreateModel(
            name='AirPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('city', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airport', to='cities_light.city')),
            ],
        ),
    ]
