# Generated by Django 4.2.6 on 2023-11-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_myuser_email_verification_code_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='activation_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
