# Generated by Django 4.2.6 on 2023-11-22 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_myuser_activation_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentcard',
            unique_together={('user', 'type')},
        ),
    ]
