# Generated by Django 4.2.6 on 2023-11-25 17:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rate', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='flights.flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookedAt', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('C', 'Cancelled'), ('A', 'Active')], default='A', max_length=1)),
                ('totalCost', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('cashBack', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('paymentMethod', models.CharField(choices=[('W', 'Wallet'), ('C', 'Card')], default='W', max_length=1)),
                ('adults', models.PositiveBigIntegerField(default=1)),
                ('kids', models.PositiveBigIntegerField(default=0)),
                ('infants', models.PositiveBigIntegerField(default=0)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookHistory', to='flights.class')),
                ('flight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flightBooks', to='flights.flight')),
                ('passenger', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookHistory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('flight', 'passenger')},
            },
        ),
    ]
