# Generated by Django 4.2.6 on 2023-11-17 22:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='offerPercentage',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
    ]
